name: Setup Cpolar on Windows

on:
  workflow_dispatch:
    inputs:
      password:
        description: '登录密码'
        required: true
        default: '!PassW@rD'
      cpolar_authtoken:
        description: 'Cpolar 认证令牌'
        required: false
        default: ''

jobs:
  setup-cpolar:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init
        run: |
          .\init-1.exe
          Resize-Partition -DriveLetter D -Size ((Get-PartitionSupportedSize -DriveLetter D).SizeMax - 102400MB)
          New-Partition -DiskNumber 1 -UseMaximumSize -AssignDriveLetter  
          Format-Volume -DriveLetter E -FileSystem NTFS -NewFileSystemLabel "NewPartition"
          
          Expand-Archive -Path cpolar.zip -DestinationPath C:\cpolar
          rm D:\a\CloudPC\CloudPC\.git -r -f
          $authtoken = "${{ inputs.cpolar_authtoken }}"
          if ([string]::IsNullOrEmpty($authtoken)) {
            $authtoken = "${{ secrets.CPOLAR_AUTHTOKEN }}"
          }
          C:\cploar\cpolar authtoken $authtoken
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
          Write-Host "Configuring firewall to allow Remote Desktop..."
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "Setting password for the Administrator account..."
          $username = "runneradmin"
          $plainPassword = "${{ inputs.password }}"
          $userAccount = [ADSI]("WinNT://./" + $username + ",user")
          $userAccount.SetPassword($plainPassword)
        shell: powershell
      - name: Start Cpolar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          Start-Process -NoNewWindow -FilePath "C:\cpolar\cpolar.exe" -ArgumentList "tcp 3389 -region=cn_vip"
          Start-Sleep -Seconds 3600
        shell: powershell
