name: Setup Cpolar on Windows

on:
  workflow_dispatch:
    inputs:
      password:
        description: '登录密码'
        required: true
        default: '!PassW@rD'

jobs:
  setup-cpolar:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init
        run: |
          Resize-Partition -DriveLetter D -Size ((Get-PartitionSupportedSize -DriveLetter D).SizeMax - 102400MB)
          New-Partition -DiskNumber 1 -UseMaximumSize -AssignDriveLetter  
          Format-Volume -DriveLetter E -FileSystem NTFS -NewFileSystemLabel "NewPartition"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
          Write-Host "Configuring firewall to allow Remote Desktop..."
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "Setting password for the Administrator account..."
          $username = "runneradmin"
          $plainPassword = "${{ inputs.password }}"
          $userAccount = [ADSI]("WinNT://./" + $username + ",user")
          $userAccount.SetPassword($plainPassword)
          Expand-Archive -Path cpolar.zip -DestinationPath E:\cpolar
          cd E:\cpolar
          cp D:\a\CloudPC\CloudPC E:\workspace -r
          .\cpolar authtoken ${{ secrets.CPOLAR_AUTHTOKEN }}
        shell: powershell
      - name: Start Cpolar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          Start-Process -NoNewWindow -FilePath "E:\cpolar\cpolar.exe" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 3600
        shell: powershell
